"""Initial Migration

Revision ID: 100649e31a74
Revises: 
Create Date: 2025-08-26 14:32:36.397655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '100649e31a74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fisioterapeutas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('crefito', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('especialidade', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('endereco', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crefito'),
    sa.UniqueConstraint('email')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('foto', sa.String(length=200), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('rua', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('foto', sa.String(length=200), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('especialidade', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('fisioterapeuta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fisioterapeuta_id'], ['fisioterapeutas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    op.drop_table('usuarios')
    op.drop_table('fisioterapeutas')
    # ### end Alembic commands ###
